# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"\x90\x01\n\x12\x43reateOrderRequest\x12\x15\n\rcustomer_name\x18\x01 \x01(\t\x12\x34\n\x06orders\x18\x02 \x03(\x0b\x32$.auth.CreateOrderRequest.OrdersEntry\x1a-\n\x0bOrdersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x8c\x01\n\x13\x43reateOrderResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x35\n\x06orders\x18\x02 \x03(\x0b\x32%.auth.CreateOrderResponse.OrdersEntry\x1a-\n\x0bOrdersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"%\n\x0cOrderRequest\x12\x15\n\rcustomer_name\x18\x01 \x01(\t\"\x80\x01\n\rOrderResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12/\n\x06orders\x18\x02 \x03(\x0b\x32\x1f.auth.OrderResponse.OrdersEntry\x1a-\n\x0bOrdersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\x0c\x41uthResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t2}\n\x0b\x41uthService\x12\x39\n\x10GetAuthenticated\x12\x11.auth.AuthRequest\x1a\x12.auth.AuthResponse\x12\x33\n\nCreateUser\x12\x11.auth.AuthRequest\x1a\x12.auth.AuthResponse2\x83\x01\n\x06Orders\x12\x34\n\tGetOrders\x12\x12.auth.OrderRequest\x1a\x13.auth.OrderResponse\x12\x43\n\x0c\x43reateOrders\x12\x18.auth.CreateOrderRequest\x1a\x19.auth.CreateOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEORDERREQUEST_ORDERSENTRY']._loaded_options = None
  _globals['_CREATEORDERREQUEST_ORDERSENTRY']._serialized_options = b'8\001'
  _globals['_CREATEORDERRESPONSE_ORDERSENTRY']._loaded_options = None
  _globals['_CREATEORDERRESPONSE_ORDERSENTRY']._serialized_options = b'8\001'
  _globals['_ORDERRESPONSE_ORDERSENTRY']._loaded_options = None
  _globals['_ORDERRESPONSE_ORDERSENTRY']._serialized_options = b'8\001'
  _globals['_CREATEORDERREQUEST']._serialized_start=21
  _globals['_CREATEORDERREQUEST']._serialized_end=165
  _globals['_CREATEORDERREQUEST_ORDERSENTRY']._serialized_start=120
  _globals['_CREATEORDERREQUEST_ORDERSENTRY']._serialized_end=165
  _globals['_CREATEORDERRESPONSE']._serialized_start=168
  _globals['_CREATEORDERRESPONSE']._serialized_end=308
  _globals['_CREATEORDERRESPONSE_ORDERSENTRY']._serialized_start=120
  _globals['_CREATEORDERRESPONSE_ORDERSENTRY']._serialized_end=165
  _globals['_ORDERREQUEST']._serialized_start=310
  _globals['_ORDERREQUEST']._serialized_end=347
  _globals['_ORDERRESPONSE']._serialized_start=350
  _globals['_ORDERRESPONSE']._serialized_end=478
  _globals['_ORDERRESPONSE_ORDERSENTRY']._serialized_start=120
  _globals['_ORDERRESPONSE_ORDERSENTRY']._serialized_end=165
  _globals['_AUTHREQUEST']._serialized_start=480
  _globals['_AUTHREQUEST']._serialized_end=529
  _globals['_AUTHRESPONSE']._serialized_start=531
  _globals['_AUTHRESPONSE']._serialized_end=577
  _globals['_AUTHSERVICE']._serialized_start=579
  _globals['_AUTHSERVICE']._serialized_end=704
  _globals['_ORDERS']._serialized_start=707
  _globals['_ORDERS']._serialized_end=838
# @@protoc_insertion_point(module_scope)
